#include <algorithm>
#include <d3dx9.h>
#include <iostream>
#include <fstream>
#include <assert.h>
#include "Utils.h"
#include "Textures.h"
#include <Windows.h>
#include <unordered_map>
#include "Sprites.h"
#include "Animations.h"
#include "GameObject.h"
#include "Sprites.h"
#include "Game.h"
#include "PlayScence.h"
#include "BeginScene.h"

#include "Mario.h"
#include "Goomba.h"
#include "Koopas.h"
#include "Portal.h"
#include "Brick.h"
#include "backRound.h"
#include "ColorBrick.h"
#include "Coin.h"
#include "MicsBrick.h"
#include "ChimneyPortal.h"
#include "LevelMushroom.h"
#include "Fire.h"
